---
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/awscredskey.yml
  tasks:
  - name: find our ami id
    ec2_ami_find:
      aws_access_key: "{{ aws_id }}"  
      aws_secret_key: "{{ aws_key }}"
      region: ap-south-1
      owner: self
      ami_tags:
        Name: mynewami
      no_result_action: fail
    register: ec2_ami_find
  - debug: msg={{ ec2_ami_find.results[0].ami_id }}
  - debug: msg={{ ec2_ami_find.results[0].name }}
  

