---
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/awscredskey.yml
  tasks:
  - name: Basic creation of vpc
    ec2_vpc:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: ap-south-1
      state: present
      cidr_block: 10.0.1.0/16
    register: vpcblock
   

      
