---
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/awscredskey.yml
  tasks:
  - name: Basic security group creation
    ec2_group:
      aws_access_key: "{{ aws_id }}"  
      aws_secret_key: "{{ aws_key }}"
      region: ap-south-1
      name: mytestgroup
      description: this is the ec2-group demo
      vpc_id: vpc-decbe6b6 
      rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0 
  

