---
- hosts: aws
  remote_user: ec2-user
  become: yes
  gather_facts: yes
  connection: local
  tasks:
  - name: Execute a shell command for listing the directory
    shell: ls -al ~
    register: result
  - name: Display the result in Json format
    debug: var=result
