---
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - ../files/awscredskey.yml
  tasks:
  - name: take a snapshot backup of the website directory
    ec2_snapshot:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: ap-south-1
      instance_ids: i-0b9384da2ceb5a70c
      device_name: /dev/xvda
      decription: initial playbook static site deployment backup
      wait: no
    register: snapshot_results
    notify: 
    - Displaysnapshotresults
    - createnewamitemplate
    - Displayamicreationresults
  handlers:
  - name: Displaysnapshotresults
    debug: var=snapshot_results
  - name: createnewamitemplate
    ec2_ami: 
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: ap-south-1
      instance_ids: i-004d9e99cd7fa
      wait: no
      name: myansibletemplate123
      tags: 
        Name: mynewansibletemplate
        Service: testamitemplate
    register: ami_results
  - name: Displayamicreationresults
    debug: var=ami_results



